<a href="https://colab.research.google.com/github/eunseojeon/NumPy/blob/main/NumPy_%EB%B0%B0%EC%97%B4_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) #인덱스 1부터 5까지의 요소를 슬라이스

[2 3 4 5]


*- 참고: 결과 에 시작 인덱스는 포함되지만 끝 인덱스는 제외됩니다 .*

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:]) #인덱스 4번부터 끝까지 출력

[5 6 7]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


**arr[1:5:2]의 의미**
- 1: 시작 인덱스(포함) → 두 번째 요소부터 (값: 2)
- 5: 끝 인덱스(미포함) → 여섯 번째 요소 전까지 (값: 6 전까지)
- 2: 간격(스텝) → 두 칸씩 건너뜀

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2]) #처음부터 끝까지 2칸씩 건너뛰며 값 추출

[1 3 5 7]


In [5]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2]) #두 요소에서 인덱스 2를 반환

[3 8]


In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
