<a href="https://colab.research.google.com/github/eunseojeon/NumPy/blob/main/NumPy%EC%9D%98_%EC%97%AC%EB%9F%AC_%EB%B0%B0%EC%97%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. 배열의 Shape

- NumPy 배열에는 shape라는 속성이 있는데,
이 속성은 각 차원의 **요소 개수를 담은 튜플을 반환**합니다.

In [52]:
#2차원 배열의 shape을 출력
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


- 배열은 2차원.
- 첫 번째 차원에는 2개의 요소가 있고 두 번째 차원에는 4개의 요소가 있다.
---



In [53]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


- ndmin값 1, 2, 3, 4를 갖는 벡터를 사용하여 5차원 배열을 만들고 마지막 차원의 값이 4인지 확인
---

# 2. NumPy 배열 재구성

- 재구성은 **배열의 모양을 바꾸는 것**을 의미
- 배열의 모양은 각 차원의 요소 수입니다.
- 재구성을 통해 차원을 **추가**하거나 **제거**할 수 있으며, 각 차원의 요소 **개수를 변경**할 수 있습니다.

In [54]:
#1차원에서 2차원으로 재구성
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
#1차원에서 3차원으로 재구성
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


---
**우리는 어떤 모양으로든 변할 수 있을까?**
- 네! 두 모양 모두 재구성에 필요한 **요소가 동일하다면 **가능합니다.
- 8개 요소의 1차원 배열을 2행 2차원 배열의 4개 요소로 재구성할 수 있지만, 3개 요소의 3행 2차원 배열로 재구성할 수는 없습니다. 재구성하려면 3x3 = 9개 요소가 필요하기 때문입니다.


In [56]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3) #->이 코드의 문제점: arr 배열의 요소 개수(8개)와 reshape(3, 3)에서 요구하는 요소 개수(3×3=9개)가 맞지 않는다는 점

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

**위의 오류를 고치면?**

In [70]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

newarr = arr.reshape(3, 3) #arr 배열의 요소 개수(9개)와 reshape(3, 3)에서 요구하는 요소 개수(3×3=9개)를 맞게 고쳐주었다.


print(newarr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 3. NumPy 배열의 반복

- **반복(iterating)**이란 요소들을 하나씩 **차례대로** 살펴보는 것을 의미합니다.
- numpy에서 **다차원 배열**을 다룰 때도 파이썬의 기본 **for 반복문**을 사용해서 이를 할 수 있습니다.
- 1차원 배열을 반복(iterate)하면 각 요소를 하나씩 차례로 살펴보게 됩니다.

In [71]:
#1차원 배열 반복
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [72]:
#2차원 배열 반복
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [73]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y) #실제 값인 스칼라를 반환하려면 각 차원의 배열을 반복해야 합니다.

1
2
3
4
5
6


---

### nditer()를 사용하여 배열 반복하기
- nditer() 함수는 매우 기본적인 반복부터 매우 고급 반복까지 사용할 수 있는 보조 함수입니다.
- 이 함수는 반복 과정에서 우리가 겪는 몇 가지 기본적인 문제를 해결해 줍니다.
### 각 스칼라 요소 반복
- 기본 for 루프를 사용할 때, 배열의 각 스칼라(단일 값)를 반복하려면 배열의 차원 수만큼 for 루프를 중첩해서 써야 합니다.
- 이렇게 하면 차원이 높은 배열의 경우 코드를 작성하기가 매우 어렵고 복잡해질 수 있습니다.

In [74]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


---
### 다른 데이터 타입으로 배열 반복
- op_dtypes 인자를 사용해서 반복하는 동안 요소의 데이터 타입을 변경하고자 할 때 원하는 데이터 타입을 지정할 수 있습니다.
- NumPy는 배열의 요소 자체(원본 배열)에서 데이터 타입을 직접 바꾸지 않기 때문에, 이 작업을 위해 별도의 공간이 필요합니다.
- 이 추가 공간을 **버퍼(buffer)**라고 하며, nditer()에서 이를 활성화하려면 **flags=['buffered']**를 전달해야 합니다.

In [75]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x) #배열의 문자열로 반복

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [76]:
#다양한 단계 크기로 반복
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


### ndenumerate()를 사용한 열거형 반복
- 열거란 어떤 것의 일련번호를 **하나하나 언급**하는 것을 의미합니다.
- 반복하는 동안 해당 요소의 인덱스가 필요한 경우가 있는데, 이 ndenumerate()메서드는 이런 사용 사례에 사용할 수 있습니다.

In [77]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


# 4. NumPy 배열 결합

- **결합**이란 두 개 이상의 배열 내용을 하나의 배열에 넣는 것을 의미합니다.

- SQL에서는 키를 기준으로 테이블을 조인하지만, NumPy에서는 축을 기준으로 배열을 조인합니다.

- 함수에 조인할 배열 시퀀스 **concatenate()**와 축을 함께 전달합니다. 축을 명시적으로 전달하지 않으면 0으로 간주됩니다.

In [78]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


---
### 스택 함수를 사용하여 배열 결합
- **스태킹**은 연결과 동일하며, 유일한 차이점은 스태킹이 새로운 축을 따라 수행된다는 것입니다.

- 두 개의 1차원 배열을 두 번째 축을 따라 연결하면 배열을 서로 겹쳐 놓을 수 있습니다. 즉, 쌓기(stacking)라고 합니다.

- 메서드 에 조인할 배열 시퀀스를 stack()축과 함께 전달합니다. 축을 명시적으로 전달하지 않으면 0으로 간주됩니다.



In [79]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


---
### 행을 따라 쌓기
- NumPy는 행을 따라 쌓기 위해 hstack()이라는 보조 함수를 제공합니다.

In [80]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


---
### 열을 따라 쌓기
- NumPy는 열 방향(세로 방향)으로 쌓기 위해 vstack()이라는 보조 함수를 제공합니다.

In [81]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


---
### 높이(깊이)에 따른 쌓기
- NumPy는 높이(깊이) 방향으로 쌓기 위해 dstack()이라는 보조 함수를 제공합니다.

In [82]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# 5. NumPy 배열 분할

- **분할(Splitting)**은 결합(Joining)의 **반대** 작업입니다.
- 결합은 여러 배열을 하나로 합치는 것이고, 분할은 하나의 배열을 여러 개로 나누는 것입니다.
- 배열을 분할할 때는 **array_split() 함수를 사용**하며, 분할하고자 하는 배열과 분할할 개수를 인자로 전달합니다.

In [83]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3) #배열을 3개 부분으로 나눔

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


---
- array_split() 메소드의 반환값은 분할된 각각의 배열을 배열 형태로 담고 있는 배열입니다.
- 만약 하나의 배열을 3개의 배열로 분할했다면, 결과에서 각 배열을 일반 배열 요소처럼 접근할 수 있습니다.

In [84]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [85]:
#2차원 배열을 3개의 2차원 배열로 분할
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


- 위의 예에서는 3개의 2차원 배열을 반환합니다.

- 또한, 분할을 기준으로 삼을 축을 지정할 수 있습니다.


---
- 다른 방법으로는, hstack()의 반대 역할을 하는 hsplit()을 사용할 수 있습니다.

In [86]:
# hsplit()방법을 사용하여 2차원 배열을 열을 따라 3개의 2차원 배열로 분할합니다.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# 6. NumPy 배열 검색

- 배열에서 **특정 값**을 **검색**하고, 일치하는 값을 찾는 인덱스를 반환할 수 있습니다.

- 배열을 검색하려면 이 **where()**메서드를 사용하세요.



In [87]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) #값 4는 인덱스 3, 5, 6에 존재

(array([3, 5, 6]),)


In [88]:
#값이 짝수인 인덱스
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [89]:
#값이 홀수인 인덱스
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


In [90]:
#값 7을 삽입해야 하는 인덱스를 찾으세요.
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


- searchsorted()방법은 정렬된 배열에 사용되는 것으로 가정
- 예시 설명: 정렬 순서를 유지하려면 숫자 7을 인덱스 1에 삽입해야 합니다.
- 이 방법은 왼쪽에서 검색을 시작하여 숫자 7이 다음 값보다 더 크지 않은 첫 번째 인덱스를 반환합니다.
---

In [60]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right') #오른쪽부터 시작하여 값 7을 삽입해야 하는 인덱스를 찾으세요.

print(x)

2


# 7. NumPy 정렬 배열

- **정렬(Sorting)**이란 요소들을 순서가 있는 **시퀀스(연속된 배열)**로 배치하는 것을 의미합니다.
- 순서가 있는 시퀀스란 숫자나 알파벳처럼 요소들에 대응되는 순서가 있는, 오름차순이나 내림차순 등의 배열을 말합니다.
- NumPy의 ndarray 객체에는 **sort()**라는 함수가 있어서, 지정한 배열을 정렬할 수 있습니다.

In [61]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [62]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr)) #알파벳 순으로 정렬

['apple' 'banana' 'cherry']


In [63]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr)) #부울의 배열을 정렬

[False  True  True]


In [64]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr)) #2차원 배열 정렬

[[2 3 4]
 [0 1 5]]


# 8. NumPy 배열 필터링

- 기존 배열에서 일부 요소를 뽑아 **새로운 배열**을 만드는 것을 **필터링(filtering)**이라고 합니다.
- NumPy에서는 **불리언 인덱스 리스트(boolean index list)**를 사용해 배열을 필터링합니다.
- 불리언 인덱스 리스트란 배열의 각 인덱스에 대응하는 불리언 값(True 또는 False)으로 이루어진 리스트입니다.
- 해당 인덱스의 값이 True이면 그 요소가 필터링된 배열에 포함되고, False이면 그 요소는 필터링된 배열에서 제외됩니다.

In [65]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr) #인덱스의 0과2의 요소로 배열 출력

[41 43]


In [66]:
#42보다 큰 값만 반환하는 필터 배열을 만듭니다.
import numpy as np

arr = np.array([41, 42, 43, 44])

# 빈 리스트 생성
filter_arr = []

# arr의 각 요소를 순회
for element in arr:
  # 만약 요소가 42보다 크면 True, 아니면 False를 추가
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [67]:
#조건에서 반복 가능한 변수 대신 배열을 직접 대체할 수 있다
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) #결과는 위와 같음

[False False  True  True]
[43 44]


In [68]:
#원래 배열에서 짝수 요소만 반환하는 필터 배열을 만듭니다.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# 빈 리스트 생성
filter_arr = []

# arr의 각 요소를 순회
for element in arr:
  # 요소가 2로 나누어 떨어지면 True, 아니면 False를 추가
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, True, False, True, False, True, False]
[2 4 6]


In [69]:
#조건에서 반복 가능한 변수 대신 배열을 직접 대체할 수 있다
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) #결과는 위와 같음

[False  True False  True False  True False]
[2 4 6]
