<a href="https://colab.research.google.com/github/eunseojeon/NumPy/blob/main/NumPy_%EB%B0%B0%EC%97%B4_%EC%83%9D%EC%84%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


- import키워드를 추가하여 애플리케이션에 가져옵니다.
---

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


- NumPy는 일반적으로 **np** 별칭으로 가져옵니다.
---

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


- 가져오는 동안 키워드 **as** 로 별칭을 만듭니다.
---

In [4]:
import numpy as np

print(np.__version__)

2.0.2


- 버전 문자열은 __version__ 속성에 저장
- 2.0.2가 출력된 이유: 현재 컴퓨터에 Numpy 2.0.2 버전이 설치되어 있기 때문
---

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


- NumPy의 배열 객체는 ndarray.

- array() 함수를 사용하여 NumPy ndarray 객체를 만들 수 있습니다.
---

In [6]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


- NumPy Arrays는 ndim배열의 차원 수를 알려주는 정수를 반환하는 속성을 제공
---

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5) #고차원 배열(여기서는 5차원)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
