<a href="https://colab.research.google.com/github/eunseojeon/NumPy/blob/main/The_Difference_Between_Copy_and_View.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Copy
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

#복사본을 만들고, 원본 배열을 변경하고, 두 배열을 모두 표시

[42  2  3  4  5]
[1 2 3 4 5]


In [2]:
#View
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

#뷰를 만들고, 원래 배열을 변경하고, 두 배열을 모두 표시

[42  2  3  4  5]
[42  2  3  4  5]


> 위에서 언급한 것처럼, 복사본(copies)은 데이터를 소유하고, 뷰(views)는 데이터를 소유하지 않습니다.
그렇다면 이것을 어떻게 확인할 수 있을까요?

> 모든 NumPy 배열에는 base라는 속성이 있습니다.
배열이 데이터를 소유하고 있다면 base 속성은 None을 반환합니다.
그렇지 않은 경우, base 속성은 원본 객체를 가리킵니다.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

# 배열이 데이터를 소유하고 있는지 확인하기 위해 기본 속성의 값을 인쇄합니다.
#복사본은 None을 반환합니다. 뷰는 원본 배열을 반환합니다.

None
[1 2 3 4 5]
